# Generated by Django 4.0.3 on 2022-03-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='tempo_Preparo',
            new_name='tempo_preparo',
        ),
    ]
